Update Github source
rumboalla/apkupdater pull request #485
Opened 2023-11-20 05:58 UTC by samuraikid0

Update k9 Github source

2023-11-21 15:30 UTC, AnonymousWP requested changes
Fixed incorrect repo name.

2023-11-21 15:30 UTC, AnonymousWP commented on app/src/main/kotlin/com/apkupdater/data/github/GitHubApp.kt
> +    GitHubApp("com.fsck.k9", "thunderbird", "android"),
```suggestion
    GitHubApp("com.fsck.k9", "thunderbird", "thunderbird-android"),
```

2023-11-22 03:33 UTC, samuraikid0 commented on app/src/main/kotlin/com/apkupdater/data/github/GitHubApp.kt
> +    GitHubApp("com.fsck.k9", "thunderbird", "android"),
My bad, it was late
Thanks !

2023-11-22 09:44 UTC, AnonymousWP approved these changes

2023-11-24 09:57 UTC, merged