Codeberg support
rumboalla/apkupdater pull request #525
Opened 2024-03-11 19:57 UTC by Jvr2022

tested

2024-03-11 20:19 UTC, rumboalla requested changes
Looking good, almost there 👍

2024-03-11 20:19 UTC, rumboalla commented on app/src/main/kotlin/com/apkupdater/data/codeberg/CodeBergApp.kt
> +fun contains(text: String) = Regex("^.*$text.*\$")
contains and notContains are duplicated

2024-03-11 20:19 UTC, rumboalla commented on app/src/main/kotlin/com/apkupdater/repository/CodeBergRepository.kt
> +        private fun selfCheck() = flow {
Everything related with selfCheck needs to be removed (it's used for apkupdater updates in GitHub source only)

2024-03-12 07:41 UTC, Jvr2022 commented on app/src/main/kotlin/com/apkupdater/repository/CodeBergRepository.kt
> +        private fun selfCheck() = flow {
fixed

2024-03-12 07:57 UTC, Jvr2022 commented on app/src/main/kotlin/com/apkupdater/data/codeberg/CodeBergApp.kt
> +fun contains(text: String) = Regex("^.*$text.*\$")
fixed

2024-03-12 08:09 UTC, Jvr2022 commented
Ready for review @rumboalla

2024-03-12 08:26 UTC, Jvr2022 commented
#394

2024-03-17 12:43 UTC, rumboalla requested changes

2024-03-17 12:43 UTC, rumboalla commented on app/src/main/kotlin/com/apkupdater/service/CodeBergService.kt
> +        @Path("user") user: String = "rumboalla",
These default values make no sense in here, they were used in GitHub source to find self-updates.

2024-03-18 07:41 UTC, Jvr2022 commented on app/src/main/kotlin/com/apkupdater/service/CodeBergService.kt
> +        @Path("user") user: String = "rumboalla",
fixed

2024-03-18 16:31 UTC, rumboalla commented
This last commit broke the build

2024-03-18 17:57 UTC, Jvr2022 commented
I am looking hownI can fix it

2024-03-24 10:06 UTC, rumboalla commented
Please reopen if you get this working.
As it is:
1) Has conflicts
2) Doesn't build.
3) Even if it built, it would not work. Looks like the CodeBerg API is not implemented properly.
4) Missing basic things. The new repo for example is not added to the Updates/Search viewmodels.

2024-03-24 10:06 UTC, closed without merging